"""Project-local ``.env`` handling for desktop and NAS operation."""

from __future__ import annotations

import os
import re
import tempfile
from pathlib import Path

MODE_DESKTOP = "desktop"
MODE_NAS = "nas"
MODE_DEMO = "demo"
DEPLOYMENT_MODES = {MODE_DESKTOP, MODE_NAS, MODE_DEMO}
PROJECT_DIR = Path(
    os.environ.get("APP_SOURCE_DIR", "").strip() or Path(__file__).resolve().parent
).resolve()
ENV_PATH = PROJECT_DIR / ".env"
ENV_EXAMPLE_PATH = PROJECT_DIR / ".env.example"
_ENV_LINE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$")


def normalize_deployment_mode(value: str | None) -> str:
    normalized = str(value or "").strip().casefold()
    return normalized if normalized in DEPLOYMENT_MODES else MODE_DESKTOP


def _decode_value(raw: str) -> str:
    value = raw.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        value = value[1:-1]
    return value


def read_env(path: Path = ENV_PATH) -> dict[str, str]:
    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        match = _ENV_LINE.match(raw_line.strip())
        if match:
            values[match.group(1)] = _decode_value(match.group(2))
    return values


def load_project_env(path: Path = ENV_PATH) -> dict[str, str]:
    """Load project defaults without overriding an explicit process environment."""
    values = read_env(path)
    for key, value in values.items():
        # Compose commonly injects optional variables as an empty string. An
        # actual value in the project .env must not be suppressed by that
        # placeholder.
        if not os.environ.get(key, ""):
            os.environ[key] = value
    return values


def _replace_values(template: str, updates: dict[str, str]) -> str:
    remaining = dict(updates)
    lines: list[str] = []
    for line in template.splitlines():
        match = _ENV_LINE.match(line.strip())
        if match and match.group(1) in remaining:
            key = match.group(1)
            lines.append(f"{key}={remaining.pop(key)}")
        else:
            lines.append(line)
    if remaining:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append("# Generated by the Royal Downloader setup")
        lines.extend(f"{key}={value}" for key, value in remaining.items())
    return "\n".join(lines).rstrip() + "\n"


def deployment_env_values(mode: str, movie_path: str, series_path: str) -> dict[str, str]:
    normalized = normalize_deployment_mode(mode)
    desktop = normalized in {MODE_DESKTOP, MODE_DEMO}
    demo = normalized == MODE_DEMO
    # NAS mode is intentionally reachable on the host network; every non-public
    # application route is fail-closed behind authentication and first-run setup
    # is protected by the one-time bootstrap token.
    nas_bind = "0.0.0.0"  # nosec B104 -- intentional authenticated NAS listener
    return {
        "ROYAL_DEPLOYMENT_MODE": normalized,
        "ROYAL_DEMO_MODE": "1" if demo else "0",
        "HOST": "127.0.0.1" if desktop else nas_bind,
        "OPEN_BROWSER": "1" if desktop else "0",
        "ROYAL_BIND_ADDRESS": "127.0.0.1" if desktop else nas_bind,
        "DNS_OVERRIDE": "0" if desktop else "1",
        "MOVIES_HOST_DIR": str(movie_path).strip(),
        "SERIES_HOST_DIR": str(series_path).strip(),
        "DOWNLOAD_DIR": str(movie_path).strip(),
        "SERIES_DIR": str(series_path).strip(),
    }


def write_project_env(
    mode: str,
    movie_path: str,
    series_path: str,
    *,
    path: Path = ENV_PATH,
    example_path: Path = ENV_EXAMPLE_PATH,
) -> dict[str, object]:
    """Create from ``.env.example`` when absent, otherwise preserve unknown keys."""
    created = not path.exists()
    if created and not example_path.is_file():
        raise FileNotFoundError(f"Vorlage fehlt: {example_path}")
    template = path.read_text(encoding="utf-8") if path.is_file() else example_path.read_text(encoding="utf-8")
    updates = deployment_env_values(mode, movie_path, series_path)
    payload = _replace_values(template, updates)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_name, path)
        try:
            path.chmod(0o600)
        except OSError:
            pass
    except Exception:
        try:
            Path(tmp_name).unlink(missing_ok=True)
        except OSError:
            pass
        raise
    return {"path": str(path), "created": created, "mode": updates["ROYAL_DEPLOYMENT_MODE"]}
