// The private language draft must also work without the online UI translator.
// Keep placeholders intact; values are inserted after selecting the template.
const languages = ["es", "fr", "it", "nl", "pl", "pt", "tr", "uk"];
const messages = [
  ["Setup steps", "Pasos de configuración", "Étapes de configuration", "Passaggi di configurazione", "Instellingsstappen", "Kroki konfiguracji", "Passos de configuração", "Kurulum adımları", "Кроки налаштування"],
  ["kept", "se conserva", "conservé", "mantenuto", "behouden", "bez zmian", "mantido", "korunur", "збережено"],
  ["Your Royal. Your language.", "Tu Royal. Tu idioma.", "Votre Royal. Votre langue.", "Il tuo Royal. La tua lingua.", "Jouw Royal. Jouw taal.", "Twój Royal. Twój język.", "O teu Royal. O teu idioma.", "Senin Royal’ın. Senin dilin.", "Твій Royal. Твоя мова."],
  ["An interface, content and subscriptions that work together.", "Una interfaz, contenidos y suscripciones que funcionan juntos.", "Une interface, des contenus et des abonnements qui fonctionnent ensemble.", "Un’interfaccia, contenuti e abbonamenti che funzionano insieme.", "Een interface, inhoud en abonnementen die samenwerken.", "Interfejs, treści i subskrypcje, które współpracują.", "Uma interface, conteúdos e subscrições que funcionam em conjunto.", "Birlikte çalışan bir arayüz, içerikler ve abonelikler.", "Інтерфейс, контент і підписки, що працюють разом."],
  ["Interface", "Interfaz", "Interface", "Interfaccia", "Interface", "Interfejs", "Interface", "Arayüz", "Інтерфейс"],
  ["Content", "Contenido", "Contenus", "Contenuti", "Inhoud", "Treści", "Conteúdos", "İçerik", "Контент"],
  ["My list", "Mi lista", "Ma liste", "La mia lista", "Mijn lijst", "Moja lista", "A minha lista", "Listem", "Мій список"],
  ["Cancel", "Cancelar", "Annuler", "Annulla", "Annuleren", "Anuluj", "Cancelar", "İptal", "Скасувати"],
  ["Back", "Atrás", "Retour", "Indietro", "Terug", "Wstecz", "Voltar", "Geri", "Назад"],
  ["Apply profile", "Aplicar perfil", "Appliquer le profil", "Applica profilo", "Profiel toepassen", "Zastosuj profil", "Aplicar perfil", "Profili uygula", "Застосувати профіль"],
  ["Continue", "Continuar", "Continuer", "Continua", "Verder", "Dalej", "Continuar", "Devam", "Далі"],
  ["How should Royal speak to you?", "¿En qué idioma debe hablarte Royal?", "Dans quelle langue Royal doit-il vous parler ?", "In quale lingua deve parlarti Royal?", "In welke taal moet Royal je aanspreken?", "W jakim języku ma mówić do Ciebie Royal?", "Em que idioma deve o Royal falar contigo?", "Royal seninle hangi dilde konuşsun?", "Якою мовою Royal має спілкуватися з тобою?"],
  ["Choose your interface language. You will choose content languages in the next step.", "Elige el idioma de la interfaz. Elegirás los idiomas del contenido en el siguiente paso.", "Choisissez la langue de l’interface. Vous choisirez les langues des contenus à l’étape suivante.", "Scegli la lingua dell’interfaccia. Sceglierai le lingue dei contenuti nel passaggio successivo.", "Kies je interfacetaal. In de volgende stap kies je de talen van de inhoud.", "Wybierz język interfejsu. Języki treści wybierzesz w następnym kroku.", "Escolhe o idioma da interface. No próximo passo, escolherás os idiomas dos conteúdos.", "Arayüz dilini seç. İçerik dillerini bir sonraki adımda seçeceksin.", "Вибери мову інтерфейсу. Мови контенту вибереш на наступному кроці."],
  ["Interface language", "Idioma de la interfaz", "Langue de l’interface", "Lingua dell’interfaccia", "Interfacetaal", "Język interfejsu", "Idioma da interface", "Arayüz dili", "Мова інтерфейсу"],
  ["Movies", "Películas", "Films", "Film", "Films", "Filmy", "Filmes", "Filmler", "Фільми"],
  ["Series", "Series", "Séries", "Serie", "Series", "Seriale", "Séries", "Diziler", "Серіали"],
  ["Your next series night.", "Tu próxima noche de series.", "Votre prochaine soirée séries.", "La tua prossima serata di serie.", "Je volgende serieavond.", "Twój kolejny wieczór z serialami.", "A tua próxima noite de séries.", "Bir sonraki dizi gecen.", "Твій наступний вечір із серіалами."],
  ["Everything you want to watch. In one place.", "Todo lo que quieres ver. En un solo lugar.", "Tout ce que vous voulez regarder. Au même endroit.", "Tutto ciò che vuoi guardare. In un unico posto.", "Alles wat je wilt kijken. Op één plek.", "Wszystko, co chcesz obejrzeć. W jednym miejscu.", "Tudo o que queres ver. Num só lugar.", "İzlemek istediğin her şey. Tek bir yerde.", "Усе, що хочеш подивитися. В одному місці."],
  ["What would you like to hear?", "¿Qué idioma quieres escuchar?", "Quelles langues souhaitez-vous entendre ?", "Quali lingue vuoi ascoltare?", "Welke talen wil je horen?", "Jakich języków chcesz słuchać?", "Que idiomas queres ouvir?", "Hangi dilleri duymak istersin?", "Які мови хочеш чути?"],
  ["Movie and series audio is independent of your interface. You can choose more than one.", "El idioma del audio de películas y series es independiente de la interfaz. Puedes elegir varios.", "La langue audio des films et séries est indépendante de l’interface. Vous pouvez en choisir plusieurs.", "La lingua audio di film e serie è indipendente dall’interfaccia. Puoi sceglierne più di una.", "De audiotaal van films en series staat los van de interface. Je kunt er meerdere kiezen.", "Język dźwięku filmów i seriali jest niezależny od interfejsu. Możesz wybrać kilka.", "O idioma do áudio dos filmes e séries é independente da interface. Podes escolher vários.", "Film ve dizilerin ses dili arayüzden bağımsızdır. Birden fazla dil seçebilirsin.", "Мова озвучення фільмів і серіалів не залежить від інтерфейсу. Можна вибрати кілька мов."],
  ["Content languages", "Idiomas del contenido", "Langues des contenus", "Lingue dei contenuti", "Talen van de inhoud", "Języki treści", "Idiomas dos conteúdos", "İçerik dilleri", "Мови контенту"],
  ["Matching sources? Taken care of.", "¿Fuentes compatibles? Listo.", "Des sources adaptées ? C’est fait.", "Fonti compatibili? Fatto.", "Passende bronnen? Geregeld.", "Pasujące źródła? Gotowe.", "Fontes compatíveis? Tratado.", "Uygun kaynaklar mı? Hazır.", "Відповідні джерела? Готово."],
  ["Royal enables matching sources and keeps your priority order. Episodes wait until matching audio is available.", "Royal activa las fuentes compatibles y mantiene tu orden de prioridad. Los episodios esperan hasta que haya audio en el idioma elegido.", "Royal active les sources adaptées et conserve votre ordre de priorité. Les épisodes attendent une piste audio correspondante.", "Royal attiva le fonti compatibili e mantiene il tuo ordine di priorità. Gli episodi attendono una traccia audio nella lingua scelta.", "Royal activeert passende bronnen en behoudt je prioriteitsvolgorde. Afleveringen wachten tot passende audio beschikbaar is.", "Royal włącza pasujące źródła i zachowuje kolejność priorytetów. Odcinki czekają na dźwięk w wybranym języku.", "O Royal ativa fontes compatíveis e mantém a tua ordem de prioridade. Os episódios aguardam áudio no idioma escolhido.", "Royal uygun kaynakları etkinleştirir ve öncelik sıranı korur. Bölümler, seçilen dilde ses sunulana kadar bekler.", "Royal вмикає відповідні джерела та зберігає порядок пріоритетів. Епізоди чекають на озвучення вибраною мовою."],
  ["Should your series switch too?", "¿También deben cambiar tus series?", "Vos séries doivent-elles aussi changer ?", "Vuoi cambiare anche le tue serie?", "Moeten je series ook overstappen?", "Czy Twoje seriale też mają zmienić język?", "As tuas séries também devem mudar?", "Dizilerin de değişsin mi?", "Змінити мову й для твоїх серіалів?"],
  ["Selected series will use the new content languages for future downloads. Others keep their current languages. Existing files and queued downloads are preserved.", "Las series seleccionadas usarán los nuevos idiomas en futuras descargas. Las demás mantendrán sus idiomas actuales. Se conservan los archivos existentes y las descargas en cola.", "Les séries sélectionnées utiliseront les nouvelles langues pour les futurs téléchargements. Les autres conserveront leurs langues actuelles. Les fichiers existants et les téléchargements en attente sont conservés.", "Le serie selezionate useranno le nuove lingue per i download futuri. Le altre manterranno le lingue attuali. I file esistenti e i download in coda vengono conservati.", "Geselecteerde series gebruiken de nieuwe talen voor toekomstige downloads. Andere behouden hun huidige talen. Bestaande bestanden en downloads in de wachtrij blijven behouden.", "Wybrane seriale będą używać nowych języków przy kolejnych pobraniach. Pozostałe zachowają obecne języki. Istniejące pliki i pobrania w kolejce pozostaną bez zmian.", "As séries selecionadas usarão os novos idiomas nas futuras transferências. As restantes mantêm os idiomas atuais. Os ficheiros existentes e as transferências em fila são preservados.", "Seçilen diziler gelecekteki indirmelerde yeni içerik dillerini kullanır. Diğerleri mevcut dillerini korur. Mevcut dosyalar ve sıradaki indirmeler korunur.", "Вибрані серіали використовуватимуть нові мови для майбутніх завантажень. Інші збережуть поточні мови. Наявні файли та завантаження в черзі залишаться без змін."],
  ["Switch all", "Cambiar todas", "Tout changer", "Cambia tutte", "Alles wijzigen", "Zmień wszystkie", "Mudar todas", "Tümünü değiştir", "Змінити всі"],
  ["Keep current languages", "Mantener los idiomas actuales", "Conserver les langues actuelles", "Mantieni le lingue attuali", "Huidige talen behouden", "Zachowaj obecne języki", "Manter os idiomas atuais", "Mevcut dilleri koru", "Зберегти поточні мови"],
  ["Your list is empty.", "Tu lista está vacía.", "Votre liste est vide.", "La tua lista è vuota.", "Je lijst is leeg.", "Twoja lista jest pusta.", "A tua lista está vazia.", "Listen boş.", "Твій список порожній."],
  ["New series will automatically use your content languages.", "Las nuevas series usarán automáticamente tus idiomas de contenido.", "Les nouvelles séries utiliseront automatiquement vos langues de contenu.", "Le nuove serie useranno automaticamente le tue lingue dei contenuti.", "Nieuwe series gebruiken automatisch je gekozen inhoudstalen.", "Nowe seriale automatycznie użyją wybranych języków treści.", "As novas séries usarão automaticamente os teus idiomas de conteúdo.", "Yeni diziler içerik dillerini otomatik olarak kullanır.", "Нові серіали автоматично використовуватимуть вибрані мови контенту."],
  ["Your new profile", "Tu nuevo perfil", "Votre nouveau profil", "Il tuo nuovo profilo", "Je nieuwe profiel", "Twój nowy profil", "O teu novo perfil", "Yeni profilin", "Твій новий профіль"],
  ["Royal is getting everything ready.", "Royal está preparándolo todo.", "Royal prépare tout.", "Royal sta preparando tutto.", "Royal maakt alles klaar.", "Royal przygotowuje wszystko.", "O Royal está a preparar tudo.", "Royal her şeyi hazırlıyor.", "Royal усе готує."],
  ["Save language profile", "Guardar perfil de idioma", "Enregistrer le profil linguistique", "Salva profilo linguistico", "Taalprofiel opslaan", "Zapisz profil językowy", "Guardar perfil de idioma", "Dil profilini kaydet", "Зберегти мовний профіль"],
  ["Prepare sources & series", "Preparar fuentes y series", "Préparer les sources et séries", "Prepara fonti e serie", "Bronnen en series voorbereiden", "Przygotuj źródła i seriale", "Preparar fontes e séries", "Kaynakları ve dizileri hazırla", "Підготувати джерела й серіали"],
  ["Prepare interface", "Preparar interfaz", "Préparer l’interface", "Prepara interfaccia", "Interface voorbereiden", "Przygotuj interfejs", "Preparar interface", "Arayüzü hazırla", "Підготувати інтерфейс"],
  ["Saving your language profile …", "Guardando tu perfil de idioma …", "Enregistrement de votre profil linguistique …", "Salvataggio del tuo profilo linguistico …", "Je taalprofiel wordt opgeslagen …", "Zapisywanie Twojego profilu językowego …", "A guardar o teu perfil de idioma …", "Dil profilin kaydediliyor …", "Збереження твого мовного профілю …"],
  ["Preparing sources and subscriptions …", "Preparando fuentes y suscripciones …", "Préparation des sources et abonnements …", "Preparazione di fonti e abbonamenti …", "Bronnen en abonnementen worden voorbereid …", "Przygotowywanie źródeł i subskrypcji …", "A preparar fontes e subscrições …", "Kaynaklar ve abonelikler hazırlanıyor …", "Підготовка джерел і підписок …"],
  ["Preparing your interface …", "Preparando tu interfaz …", "Préparation de votre interface …", "Preparazione della tua interfaccia …", "Je interface wordt voorbereid …", "Przygotowywanie Twojego interfejsu …", "A preparar a tua interface …", "Arayüzün hazırlanıyor …", "Підготовка твого інтерфейсу …"],
  ["Everything is ready.", "Todo está listo.", "Tout est prêt.", "È tutto pronto.", "Alles is klaar.", "Wszystko gotowe.", "Está tudo pronto.", "Her şey hazır.", "Усе готово."],
  ["Try again", "Reintentar", "Réessayer", "Riprova", "Opnieuw proberen", "Spróbuj ponownie", "Tentar novamente", "Tekrar dene", "Спробувати ще раз"],
  ["Choose at least one language with movie and series sources.", "Elige al menos un idioma con fuentes de películas y series.", "Choisissez au moins une langue avec des sources de films et de séries.", "Scegli almeno una lingua con fonti di film e serie.", "Kies minstens één taal met film- en seriebronnen.", "Wybierz co najmniej jeden język ze źródłami filmów i seriali.", "Escolhe pelo menos um idioma com fontes de filmes e séries.", "Film ve dizi kaynakları bulunan en az bir dil seç.", "Вибери хоча б одну мову з джерелами фільмів і серіалів."],
  ["{changed} of {total} series will use the new content languages.", "{changed} de {total} series usarán los nuevos idiomas de contenido.", "{changed} séries sur {total} utiliseront les nouvelles langues de contenu.", "{changed} serie su {total} useranno le nuove lingue dei contenuti.", "{changed} van {total} series gebruiken de nieuwe inhoudstalen.", "{changed} z {total} seriali będzie używać nowych języków treści.", "{changed} de {total} séries usarão os novos idiomas de conteúdo.", "{total} diziden {changed} tanesi yeni içerik dillerini kullanacak.", "{changed} із {total} серіалів використовуватимуть нові мови контенту."],
  ["Profile saved. Preparation is not finished: {error}", "Perfil guardado. La preparación no ha terminado: {error}", "Profil enregistré. La préparation n’est pas terminée : {error}", "Profilo salvato. La preparazione non è terminata: {error}", "Profiel opgeslagen. De voorbereiding is nog niet klaar: {error}", "Profil zapisany. Przygotowanie nie zostało zakończone: {error}", "Perfil guardado. A preparação ainda não terminou: {error}", "Profil kaydedildi. Hazırlık henüz tamamlanmadı: {error}", "Профіль збережено. Підготовку ще не завершено: {error}"],
  ["Royal cannot load your language profile right now. Please try again. Nothing has changed.", "Royal no puede cargar tu perfil de idioma ahora. Inténtalo de nuevo. No se ha cambiado nada.", "Royal ne peut pas charger votre profil linguistique pour le moment. Réessayez. Rien n’a été modifié.", "Royal non può caricare il tuo profilo linguistico al momento. Riprova. Non è stato modificato nulla.", "Royal kan je taalprofiel nu niet laden. Probeer het opnieuw. Er is niets gewijzigd.", "Royal nie może teraz wczytać Twojego profilu językowego. Spróbuj ponownie. Nic nie zostało zmienione.", "O Royal não consegue carregar o teu perfil de idioma agora. Tenta novamente. Nada foi alterado.", "Royal şu anda dil profilini yükleyemiyor. Lütfen tekrar dene. Hiçbir şey değişmedi.", "Royal зараз не може завантажити твій мовний профіль. Спробуй ще раз. Нічого не змінено."],
  ["Loading your language profile …", "Cargando tu perfil de idioma …", "Chargement de votre profil linguistique …", "Caricamento del tuo profilo linguistico …", "Je taalprofiel wordt geladen …", "Wczytywanie Twojego profilu językowego …", "A carregar o teu perfil de idioma …", "Dil profilin yükleniyor …", "Завантаження твого мовного профілю …"],
];

export const LANGUAGE_SETUP_COPY = Object.fromEntries(languages.map((language, index) => [
  language, Object.fromEntries(messages.map(([key, ...values]) => [key, values[index]])),
]));

export function languageSetupText(language, german, english, values = {}) {
  const code = String(language || "de").toLowerCase().replaceAll("_", "-").split("-")[0];
  const template = code === "en" ? english : LANGUAGE_SETUP_COPY[code]?.[english] || german;
  return template.replace(/\{(\w+)\}/g, (placeholder, key) => Object.hasOwn(values, key) ? String(values[key]) : placeholder);
}
