function aniworldBrowse(...args) { return sharedPresentation.aniworld.browse(...args); }
function loadNextAniworldPage(...args) { return sharedPresentation.aniworld.next(...args); }
function openAniworldDetail(...args) { return sharedPresentation.aniworld.open(...args); }
function loadAniworldDetail(...args) { return sharedPresentation.aniworld.loadDetail(...args); }
function renderAniworldResults(...args) { return sharedPresentation.aniworld.renderResults(...args); }
function renderAniworldDetail(...args) { return sharedPresentation.aniworld.renderDetail(...args); }
function renderAniworldEpisodes(...args) { return sharedPresentation.aniworld.renderEpisodes(...args); }
function syncAniworldQueueFlags(...args) { return sharedPresentation.aniworld.syncQueue(...args); }
function markAniworldSlugDownloaded(...args) { return sharedPresentation.aniworld.markDownloaded(...args); }
function aniworldAddSelected(...args) { return sharedPresentation.aniworld.addSelected(...args); }
function aniworldVisibleEpisodes(...args) { return sharedPresentation.aniworld.visibleEpisodes(...args); }
function aniworldSelectableEpisodes(...args) { return sharedPresentation.aniworld.selectableEpisodes(...args); }
function updateAniworldInfiniteState(...args) { return sharedPresentation.aniworld.updateInfinite(...args); }
