function firstEpisodeSlug(...args) { return sharedPresentation.seriesEpisodes.firstEpisodeSlug(...args); }
function seriesEpisodes(...args) { return sharedPresentation.seriesEpisodes.seriesEpisodes(...args); }
function isEpisodeQueued(...args) { return sharedPresentation.seriesEpisodes.isEpisodeQueued(...args); }
function episodeHasEnabledStreamLanguage(...args) { return sharedPresentation.seriesEpisodes.episodeHasEnabledStreamLanguage(...args); }
function episodeLanguageLockLabel(...args) { return sharedPresentation.seriesEpisodes.episodeLanguageLockLabel(...args); }
function isEpisodeEligible(...args) { return sharedPresentation.seriesEpisodes.isEpisodeEligible(...args); }
function isEpisodeSelectable(...args) { return sharedPresentation.seriesEpisodes.isEpisodeSelectable(...args); }
function isEpisodeActionable(...args) { return sharedPresentation.seriesEpisodes.isEpisodeActionable(...args); }
function syncSeriesQueueFlags(...args) { return sharedPresentation.seriesEpisodes.syncSeriesQueueFlags(...args); }
function pruneSeriesEpisodeSelection(...args) { return sharedPresentation.seriesEpisodes.pruneSeriesEpisodeSelection(...args); }
function findCurrentEpisode(...args) { return sharedPresentation.seriesEpisodes.findCurrentEpisode(...args); }
function tileClass(...args) { return sharedPresentation.seriesEpisodes.tileClass(...args); }
function episodeReleaseText(...args) { return sharedPresentation.seriesEpisodes.episodeReleaseText(...args); }
function seriesAvailabilityNotice(...args) { return sharedPresentation.seriesEpisodes.seriesAvailabilityNotice(...args); }
function syncSeriesAvailabilityNotice(...args) { return sharedPresentation.seriesEpisodes.syncSeriesAvailabilityNotice(...args); }
function applySeriesEpisodeTileState(...args) { return sharedPresentation.seriesEpisodes.applySeriesEpisodeTileState(...args); }
function refreshSeriesTileStates(...args) { return sharedPresentation.seriesEpisodes.refreshSeriesTileStates(...args); }
function renderSeriesTiles(...args) { return sharedPresentation.seriesEpisodes.renderSeriesTiles(...args); }
function toggleEpisodeTile(...args) { return sharedPresentation.seriesEpisodes.toggleEpisodeTile(...args); }
function toggleSeasonTiles(...args) { return sharedPresentation.seriesEpisodes.toggleSeasonTiles(...args); }
function selectAllSeriesEpisodes(...args) { return sharedPresentation.seriesEpisodes.selectAllSeriesEpisodes(...args); }
function markSeriesSlugDownloaded(...args) { return sharedPresentation.seriesEpisodes.markSeriesSlugDownloaded(...args); }
function seriesAddSelected(...args) { return sharedPresentation.seriesEpisodes.seriesAddSelected(...args); }
function verifyHuhuEpisodeLanguages(...args) { return sharedPresentation.seriesChecks.verifyLanguages(...args); }
function clearSeriesSearchContext(...args) { return sharedPresentation.seriesBrowse.clear(...args); }
function rememberSeriesSearchContext(...args) { return sharedPresentation.seriesBrowse.remember(...args); }
function restoreSeriesSearchContext(...args) { return sharedPresentation.seriesBrowse.restore(...args); }
function seriesSearch(...args) { return sharedPresentation.seriesBrowse.search(...args); }
function seriesBrowse(...args) { return sharedPresentation.seriesBrowse.browse(...args); }
function ensureSeriesResults(...args) { return sharedPresentation.seriesBrowse.ensure(...args); }
function loadNextSeriesPage(...args) { return sharedPresentation.seriesBrowse.next(...args); }
function mergeSeriesDetailPayload(...args) { return sharedPresentation.seriesDetailsLoader.merge(...args); }
function loadSeries(...args) { return sharedPresentation.seriesDetailsLoader.open(...args); }
function stopSeriesDetailHeroTrailer() { return sharedPresentation.trailers.series.stop(); }
function scheduleSeriesDetailHeroTrailer(series) { return sharedPresentation.trailers.series.schedule(series); }
function configureSeriesTrailer(series) { return sharedPresentation.trailers.series.configure(series); }
function updateSeriesInfiniteState(...args) { return sharedPresentation.seriesPresentation.updateSeriesInfiniteState(...args); }
function updateSeriesFeatureArtwork(...args) { return sharedPresentation.seriesPresentation.updateSeriesFeatureArtwork(...args); }
function renderSeriesCatalogHero(...args) { return sharedPresentation.seriesPresentation.renderSeriesCatalogHero(...args); }
function seriesCardSeasonSummary(...args) { return sharedPresentation.seriesPresentation.seriesCardSeasonSummary(...args); }
function createSeriesResultRow(...args) { return sharedPresentation.seriesPresentation.createSeriesResultRow(...args); }
function renderSeriesResults(...args) { return sharedPresentation.seriesPresentation.renderSeriesResults(...args); }
function findSeriesResultCard(...args) { return sharedPresentation.seriesPresentation.findSeriesResultCard(...args); }
function updateSeriesResultCard(...args) { return sharedPresentation.seriesPresentation.updateSeriesResultCard(...args); }
function updateSeriesResultSelection(...args) { return sharedPresentation.seriesPresentation.updateSeriesResultSelection(...args); }
function applySeriesResults(...args) { return sharedPresentation.seriesPresentation.applySeriesResults(...args); }
function seriesStructureFingerprint(...args) { return sharedPresentation.seriesPresentation.seriesStructureFingerprint(...args); }
function showSeriesLoading(...args) { return sharedPresentation.seriesPresentation.showSeriesLoading(...args); }
function renderSeriesDetailMeta(...args) { return sharedPresentation.seriesPresentation.renderSeriesDetailMeta(...args); }
function updateWatchBtn(...args) { return sharedPresentation.seriesPresentation.updateWatchBtn(...args); }
function setSeriesDetailArtwork(...args) { return sharedPresentation.seriesPresentation.setSeriesDetailArtwork(...args); }
function updateSeriesOverview(...args) { return sharedPresentation.seriesPresentation.updateSeriesOverview(...args); }
function showSeriesDetail(...args) { return sharedPresentation.seriesPresentation.showSeriesDetail(...args); }
function renderSeriesDetailDiscovery(...args) { return sharedPresentation.seriesDiscovery.render(...args); }
