import { sharedPresentation } from "../presentation.js";
export function firstEpisodeSlug(...args) { return sharedPresentation.seriesEpisodes.firstEpisodeSlug(...args); }
export function seriesEpisodes(...args) { return sharedPresentation.seriesEpisodes.seriesEpisodes(...args); }
export function isEpisodeQueued(...args) { return sharedPresentation.seriesEpisodes.isEpisodeQueued(...args); }
export function episodeHasEnabledStreamLanguage(...args) { return sharedPresentation.seriesEpisodes.episodeHasEnabledStreamLanguage(...args); }
export function episodeLanguageLockLabel(...args) { return sharedPresentation.seriesEpisodes.episodeLanguageLockLabel(...args); }
export function isEpisodeEligible(...args) { return sharedPresentation.seriesEpisodes.isEpisodeEligible(...args); }
export function isEpisodeSelectable(...args) { return sharedPresentation.seriesEpisodes.isEpisodeSelectable(...args); }
export function isEpisodeActionable(...args) { return sharedPresentation.seriesEpisodes.isEpisodeActionable(...args); }
export function syncSeriesQueueFlags(...args) { return sharedPresentation.seriesEpisodes.syncSeriesQueueFlags(...args); }
export function pruneSeriesEpisodeSelection(...args) { return sharedPresentation.seriesEpisodes.pruneSeriesEpisodeSelection(...args); }
export function findCurrentEpisode(...args) { return sharedPresentation.seriesEpisodes.findCurrentEpisode(...args); }
export function tileClass(...args) { return sharedPresentation.seriesEpisodes.tileClass(...args); }
export function episodeReleaseText(...args) { return sharedPresentation.seriesEpisodes.episodeReleaseText(...args); }
export function seriesAvailabilityNotice(...args) { return sharedPresentation.seriesEpisodes.seriesAvailabilityNotice(...args); }
export function syncSeriesAvailabilityNotice(...args) { return sharedPresentation.seriesEpisodes.syncSeriesAvailabilityNotice(...args); }
export function applySeriesEpisodeTileState(...args) { return sharedPresentation.seriesEpisodes.applySeriesEpisodeTileState(...args); }
export function refreshSeriesTileStates(...args) { return sharedPresentation.seriesEpisodes.refreshSeriesTileStates(...args); }
export function renderSeriesTiles(...args) { return sharedPresentation.seriesEpisodes.renderSeriesTiles(...args); }
export function toggleEpisodeTile(...args) { return sharedPresentation.seriesEpisodes.toggleEpisodeTile(...args); }
export function toggleSeasonTiles(...args) { return sharedPresentation.seriesEpisodes.toggleSeasonTiles(...args); }
export function selectAllSeriesEpisodes(...args) { return sharedPresentation.seriesEpisodes.selectAllSeriesEpisodes(...args); }
export function markSeriesSlugDownloaded(...args) { return sharedPresentation.seriesEpisodes.markSeriesSlugDownloaded(...args); }
export function seriesAddSelected(...args) { return sharedPresentation.seriesEpisodes.seriesAddSelected(...args); }
export function verifyHuhuEpisodeLanguages(...args) { return sharedPresentation.seriesChecks.verifyLanguages(...args); }
export function clearSeriesSearchContext(...args) { return sharedPresentation.seriesBrowse.clear(...args); }
export function rememberSeriesSearchContext(...args) { return sharedPresentation.seriesBrowse.remember(...args); }
export function restoreSeriesSearchContext(...args) { return sharedPresentation.seriesBrowse.restore(...args); }
export function seriesSearch(...args) { return sharedPresentation.seriesBrowse.search(...args); }
export function seriesBrowse(...args) { return sharedPresentation.seriesBrowse.browse(...args); }
export function ensureSeriesResults(...args) { return sharedPresentation.seriesBrowse.ensure(...args); }
export function loadNextSeriesPage(...args) { return sharedPresentation.seriesBrowse.next(...args); }
export function mergeSeriesDetailPayload(...args) { return sharedPresentation.seriesDetailsLoader.merge(...args); }
export function loadSeries(...args) { return sharedPresentation.seriesDetailsLoader.open(...args); }
export function stopSeriesDetailHeroTrailer() { return sharedPresentation.trailers.series.stop(); }
export function scheduleSeriesDetailHeroTrailer(series) { return sharedPresentation.trailers.series.schedule(series); }
export function configureSeriesTrailer(series) { return sharedPresentation.trailers.series.configure(series); }
export function updateSeriesInfiniteState(...args) { return sharedPresentation.seriesPresentation.updateSeriesInfiniteState(...args); }
export function updateSeriesFeatureArtwork(...args) { return sharedPresentation.seriesPresentation.updateSeriesFeatureArtwork(...args); }
export function renderSeriesCatalogHero(...args) { return sharedPresentation.seriesPresentation.renderSeriesCatalogHero(...args); }
export function seriesCardSeasonSummary(...args) { return sharedPresentation.seriesPresentation.seriesCardSeasonSummary(...args); }
export function createSeriesResultRow(...args) { return sharedPresentation.seriesPresentation.createSeriesResultRow(...args); }
export function renderSeriesResults(...args) { return sharedPresentation.seriesPresentation.renderSeriesResults(...args); }
export function findSeriesResultCard(...args) { return sharedPresentation.seriesPresentation.findSeriesResultCard(...args); }
export function updateSeriesResultCard(...args) { return sharedPresentation.seriesPresentation.updateSeriesResultCard(...args); }
export function updateSeriesResultSelection(...args) { return sharedPresentation.seriesPresentation.updateSeriesResultSelection(...args); }
export function applySeriesResults(...args) { return sharedPresentation.seriesPresentation.applySeriesResults(...args); }
export function seriesStructureFingerprint(...args) { return sharedPresentation.seriesPresentation.seriesStructureFingerprint(...args); }
export function showSeriesLoading(...args) { return sharedPresentation.seriesPresentation.showSeriesLoading(...args); }
export function renderSeriesDetailMeta(...args) { return sharedPresentation.seriesPresentation.renderSeriesDetailMeta(...args); }
export function updateWatchBtn(...args) { return sharedPresentation.seriesPresentation.updateWatchBtn(...args); }
export function setSeriesDetailArtwork(...args) { return sharedPresentation.seriesPresentation.setSeriesDetailArtwork(...args); }
export function updateSeriesOverview(...args) { return sharedPresentation.seriesPresentation.updateSeriesOverview(...args); }
export function showSeriesDetail(...args) { return sharedPresentation.seriesPresentation.showSeriesDetail(...args); }
export function renderSeriesDetailDiscovery(...args) { return sharedPresentation.seriesDiscovery.render(...args); }
